In [16]:
# task 1.1
import numpy as np
A = np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
B = np.array([[7, 5, 3], [0, 7, 5], [0, 0, 7]])
AB = A.dot(B)
BA = B.dot(A)
C=AB-BA
print(AB,'\n','-','\n',BA,'\n','=' ,'\n',C)

[[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]] 
 - 
 [[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]] 
 = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
# task 1.2
a=float(input());b=float(input());c=float(input());d=float(input())
A = np.array([[a,0,0,0], [0,b,0,0], [0,0,c,0], [0,0,0,d]])
print(A.dot(A))

[[ 1.  0.  0.  0.]
 [ 0.  4.  0.  0.]
 [ 0.  0.  9.  0.]
 [ 0.  0.  0. 16.]]


In [30]:
# task 1.3
A = np.array([[3], [1], [-1], [5], [2]])
B = np.array([[4, 0, -2,3,1]])
print(A.dot(B))

[[ 12   0  -6   9   3]
 [  4   0  -2   3   1]
 [ -4   0   2  -3  -1]
 [ 20   0 -10  15   5]
 [  8   0  -4   6   2]]


In [29]:
# task 1.4
A = np.array([[1,5,-5], [4,0,3], [2,-10,3]])
print(format(np.linalg.det(A), '.9g'))

200


In [33]:
# task 1.5
A = np.array([[1,2,0,0,0], [1,0,2,0,0], [1,0,0,2,0], [1,0,0,0,2], [0,0,1,1,1]])
print(format(np.linalg.det(A), '.9g'))

-24


In [34]:
# task 1.6
A = np.array([[1,1,1,1], [1,1,-1,-1], [1,-1,1,-1], [1,-1,-1,1]])
print(np.linalg.inv(A))

[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]


In [173]:
# task 1.7
A = np.array([[-2,3,1,-1], [3,2,1,4], [1,2,3,4], [0,2,3,3]])
print(np.linalg.matrix_rank(A))

3


In [172]:
# task 1.8.1 Kramer
def det(n):
    d=n[0,0]*n[1,1]*n[2,2]+n[0,1]*n[1,2]*n[2,0]+n[1,0]*n[2,1]*n[0,2]-n[0,2]*n[1,1]*n[2,0]-n[0,1]*n[1,0]*n[2,2]-n[1,2]*n[2,1]*n[0,0]
    return d
A = np.matrix('1 -2 1;2 -1 1;3 2 2')
B = np.matrix('4;3;2')
def method_1(a,b):
    di=[0,0,0]
    X=[0,0,0]
    d=det(a)
    A_1=np.matrix(a)
    for j in range(0,3):
        for i in range(0,3):
            A_1[i,j]=B[i]
        di[j]=det(A_1)
        X[j]=di[j]/d
        A_1=np.matrix(a)
        
    return X
print(method_1(A,B))


[0.0, -1.0, 2.0]


In [171]:
# task 1.8.1 checking
a = np.matrix('1. -2. 1.;2. -1. 1.;3. 2. 2.')
b = np.matrix('4.;3.;2.')
x = np.linalg.solve(a,b)
print('x=',int(x[0])) # Коли х = 0 виводить велике число
print('y=',x[1])
print('z=',x[2])


x= 0
y= [[-1.]]
z= [[2.]]


In [170]:
# task 1.8.2 Matrix
a = np.matrix('1 -2 1;2 -1 1;3 2 2')
b = np.matrix('4;3;2')
X=[0,0,0]
def method_2(a,b):
    x=np.linalg.inv(a).dot(b)
    return (x)
X = method_2(a,b)
print('x=',int(X[0])) # Коли х = 0 виводить велике число
print('y=',X[1])
print('z=',X[2])

x= 0
y= [[-1.]]
z= [[2.]]


In [222]:
# task 2 (without numpy)
from random import randint
def printMatrix( A ):
     for i in range(len(A)): 
        for j in range(len(A[i])): 
            print( "{:4d}".format(A[i][j]), end="" ) 
        print()
N=int(input());M=int(input())
s_c=[ [0] for j in range(M) ]
s_r=[ [0] for i in range(N)]
summ_c1=float(0)
summ_r1=float(0)

A = [ [0]*M for i in range(N) ]
for i in range(N):  
    for j in range(M): 
        A[i][j] = randint( 0, 10 ) # Підбір випадкових чисел від 0 до 10
        x=float(A[i][j])
       
        summ_r1 += x   # Середні значення стобців
    s_r[i]=summ_r1/M
    summ_r1=0
for j in range(M):
     for i in range(N):
        x=A[i][j]
       
        summ_c1 += x   # Середні значення рядків
     s_c[j]=summ_c1/N
     summ_c1=0
    



printMatrix( A )
print('Average values ​​of the columns = ',s_c )
print('Average values ​​of rows= ',s_r )




   6   0   4
   3   2   5
Average values ​​of the columns [4.5, 1.0, 4.5]
Average values ​​of rows [3.3333333333333335, 3.3333333333333335]
